#!/usr/bin/sh

git config user.email "g_kl_es_sing_er@gmx.de"

versioning=calver
#lit_prog_eval_match="on_demand" # we use locks
# list of '::' seperated words to fail when occurring in committed files:
blacklisted_words="$(pass show sensitive/axgkl)"
