site_name: "AXGK Blog"
site_description: "Random Thoughts"
site_url: "https://AXGKl.github.io/blog/"
repo_url: "https://github.com/AXGKl/blog"
repo_name: "AXGKl/blog"
edit_uri: editor:///home/gk/repos/blog/docs

copyright: |
  Copyright &copy; Gunther Klessinger

#
nav:
  - Overview: index.md
  - CloudTech:
      - DNSMasq: cloud/dnsmasq/index.md
      - Github Actions: cloud/ci/github_actions.md
      - Kubernetes:
          - Notes: cloud/k8s/index.md
          - K9s Terminal UI: cloud/k8s/k9s/k9s.md
          - First App: cloud/k8s/1_hello_app/index.md
          - With DB: cloud/k8s/2_hello_mysql/index.md
      - Terraform:
          - About: cloud/terraform/index.md
          - Basic Operation: cloud/terraform/resource_creation.md
          - TF And Ansible: cloud/terraform/ansible.md
          - Kubernetes: cloud/terraform/k8s/index.md
          - K8s Cluster Infra: cloud/terraform/k8s/k8s_on_do.md
          - Attaching Using Token Only: cloud/terraform/k8s/k8s_provider/do_k8s.md
          - The K8s Provider: cloud/terraform/k8s/k8s_provider/k8s_provider.md
  - LinuxLocal:
      - Apps: ll/apps/apps.md
      - Devices: ll/devices/tv_q8.md
      - Distros: ll/distro.md
      - Emacs: ll/emacs/emacs.md
      - Gimp: ll/gimp/gimp.md
      - Hardware:
          - Keyboards General: ll/hw/k860.md
          - Keyboards Corne: ll/hw/corne.md
      - MkDocs: ll/mkdocs/mkdocs.md
      - Suckless:
          - About: ll/sl/about.md
          - dwm: ll/sl/dwm.md
          - st: ll/sl/st.md
          - Statusbar Fun:
              - The Problem: ll/sl/status_bar_fun/2021.05.23_dwm_status_1_a_fancy_status_bar.md
              - XFCE: ll/sl/status_bar_fun/2021.05.24_dwm_status_2_never_call_xsession_within_dwm.md
              - XFCE Panel in DWM: ll/sl/status_bar_fun/2021.05.24_dwm_status_3_xfce4_panel_in_dwm.md
              - CPU Monitor: ll/sl/status_bar_fun/2021.05.24_dwm_status_4_adding_our_monitor.md
      - Vim:
          - About: ll/vim/vim.md
          - Ultisnips: ll/vim/ultisnips.md
      - Fun:
          - Einstein: ll/fun/einstein.md
          - UnblockMe: ll/fun/unblockme/index.md

  - Videos And Tutorials: inet/videos.md
  - Logbook: logbook.md

  - About:
      - Changelog: about/changelog.md
      - Credits: about/credits.md

theme:
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.sections
      #- toc.integrate
    - navigation.expand
  name: material
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: preference
    primary: black
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
    #- toc.autohide

markdown_extensions:
  - admonition
  - attr_list # {: style="height: ..."}
  - footnotes # foo[^1] is ...(start with ^)
  - meta
  - markdown_include.include
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - markdown.extensions.tables
  - markdown.extensions.footnotes
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
  - toc:
      permalink: "¤"
  - pymdownx.snippets:
      base_path:
        - docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/axiros

plugins:
  # in this order. e.g. md-replace before lp, so that lp can process its results
  - search
  - lcd-blacklist
  - lcd-md-replace
  - lcd-lp
  - lcd-page-tree
  - lcd-stats
  - macros:
      j2_block_start_string: "<%{"
      j2_block_end_string: "}%>"
      j2_variable_start_string: "<{"
      j2_variable_end_string: "}>"
