{'1fe2d96bbb24a005f57dbc0281ae61c2': [{'cmd': 'for p in rx gevent flask; do '
                                              'pip show $p || pip install $p; '
                                              'done',
                                       'res': '$ for p in rx gevent flask; do '
                                              'pip show $p || pip install $p; '
                                              'done\n'
                                              'Name: Rx\n'
                                              'Version: 3.2.0\n'
                                              'Summary: Reactive Extensions '
                                              '(Rx) for Python\n'
                                              'Home-page: http://reactivex.io\n'
                                              'Author: Dag Brattli\n'
                                              'Author-email: dag@brattli.net\n'
                                              'License: MIT License\n'
                                              'Location: '
                                              '/home/gk/miniconda3/envs/blog_py3.9/lib/python3.9/site-packages\n'
                                              'Requires: \n'
                                              'Required-by: \n'
                                              'Name: gevent\n'
                                              'Version: 21.12.0\n'
                                              'Summary: Coroutine-based '
                                              'network library\n'
                                              'Home-page: '
                                              'http://www.gevent.org/\n'
                                              'Author: Denis Bilenko\n'
                                              'Author-email: '
                                              'denis.bilenko@gmail.com\n'
                                              'License: MIT\n'
                                              'Location: '
                                              '/home/gk/miniconda3/envs/blog_py3.9/lib/python3.9/site-packages\n'
                                              'Requires: greenlet, setuptools, '
                                              'zope.event, zope.interface\n'
                                              'Required-by: \n'
                                              'WARNING: Package(s) not found: '
                                              'flask\n'
                                              'Looking in indexes: '
                                              'https://pypi.org/simple, '
                                              'https://klessinger:****@artifacts.axiros.com/artifactory/api/pypi/pypi-ax-sources/simple\n'
                                              'Collecting flask\n'
                                              '  Using cached '
                                              'Flask-2.0.3-py3-none-any.whl '
                                              '(95 kB)\n'
                                              'Collecting Jinja2>=3.0\n'
                                              '  Using cached '
                                              'Jinja2-3.0.3-py3-none-any.whl '
                                              '(133 kB)\n'
                                              'Collecting itsdangerous>=2.0\n'
                                              '  Using cached '
                                              'itsdangerous-2.1.1-py3-none-any.whl '
                                              '(15 kB)\n'
                                              'Requirement already satisfied: '
                                              'click>=7.1.2 in '
                                              '/home/gk/miniconda3/envs/blog_py3.9/lib/python3.9/site-packages '
                                              '(from flask) (8.0.4)\n'
                                              'Collecting Werkzeug>=2.0\n'
                                              '  Using cached '
                                              'Werkzeug-2.0.3-py3-none-any.whl '
                                              '(289 kB)\n'
                                              'Requirement already satisfied: '
                                              'MarkupSafe>=2.0 in '
                                              '/home/gk/miniconda3/envs/blog_py3.9/lib/python3.9/site-packages '
                                              '(from Jinja2>=3.0->flask) '
                                              '(2.0.1)\n'
                                              'Installing collected packages: '
                                              'Werkzeug, Jinja2, itsdangerous, '
                                              'flask\n'
                                              '  Attempting uninstall: Jinja2\n'
                                              '    Found existing '
                                              'installation: Jinja2 2.11.3\n'
                                              '    Uninstalling '
                                              'Jinja2-2.11.3:\n'
                                              '      Successfully uninstalled '
                                              'Jinja2-2.11.3\n'
                                              "ERROR: pip's dependency "
                                              'resolver does not currently '
                                              'take into account all the '
                                              'packages that are installed. '
                                              'This behaviour is the source of '
                                              'the following dependency '
                                              'conflicts.\n'
                                              'git-changelog 0.4.2 requires '
                                              'Jinja2<3.0,>=2.10, but you have '
                                              'jinja2 3.0.3 which is '
                                              'incompatible.\n'
                                              'diagrams 0.20.0 requires '
                                              'jinja2<3.0,>=2.10, but you have '
                                              'jinja2 3.0.3 which is '
                                              'incompatible.\n'
                                              'Successfully installed '
                                              'Jinja2-3.0.3 Werkzeug-2.0.3 '
                                              'flask-2.0.3 '
                                              'itsdangerous-2.1.1'}],
 '344fd121704d5dce8bb543248f0febd5': [{'cmd': 'python tests/rx/tools.py',
                                       'res': '$ python tests/rx/tools.py\n'
                                              '\x1b[0;38;5;245m    4\x1b[0m  M '
                                              '\x1b[31m[S] msg 1\x1b[0m\n'
                                              '\x1b[0;38;5;245m   54\x1b[0m  M '
                                              '\x1b[33m[2] async msg\x1b[0m\n'
                                              '\x1b[0;38;5;245m   54\x1b[0m  M '
                                              '\x1b[34m[3] async msg\x1b[0m\n'
                                              '\x1b[0;38;5;245m   54\x1b[0m  M '
                                              '\x1b[31m[S] async msg\x1b[0m\n'
                                              '\x1b[0;38;5;245m  104\x1b[0m  M '
                                              '\x1b[35m[4] msg 3\x1b[0m'},
                                      {'cmd': 'python tests/rx/tools.py '
                                              'patched',
                                       'res': '$ python tests/rx/tools.py '
                                              'patched\n'
                                              '\x1b[0;38;5;245m  149\x1b[0m  M '
                                              '\x1b[31m[S] msg 1\x1b[0m\n'
                                              '\x1b[0;38;5;245m  199\x1b[0m  1 '
                                              '\x1b[33m[2] async msg\x1b[0m\n'
                                              '\x1b[0;38;5;245m  199\x1b[0m  2 '
                                              '\x1b[34m[3] async msg\x1b[0m\n'
                                              '\x1b[0;38;5;245m  199\x1b[0m  3 '
                                              '\x1b[31m[S] async msg\x1b[0m\n'
                                              '\x1b[0;38;5;245m  249\x1b[0m  M '
                                              '\x1b[35m[4] msg 3\x1b[0m'}],
 '6d9bd4e903932ff33bd8de1cdcfadc31': [{'cmd': 'pytest -xs '
                                              'tests/rx/test_async_server.py '
                                              '-k one 2>/dev/null',
                                       'res': '$ pytest -xs '
                                              'tests/rx/test_async_server.py '
                                              '-k one 2>/dev/null\n'
                                              '============================= '
                                              'test session starts '
                                              '==============================\n'
                                              'platform linux -- Python '
                                              '3.9.10, pytest-6.2.5, '
                                              'py-1.11.0, pluggy-1.0.0\n'
                                              'Using '
                                              '--randomly-seed=2560039460\n'
                                              'rootdir: /home/gk/repos\n'
                                              'plugins: forked-1.4.0, '
                                              'randomly-3.11.0, cov-2.12.1, '
                                              'xdist-2.5.0, sugar-0.9.4\n'
                                              'collected 2 items / 1 '
                                              'deselected / 1 selected\n'
                                              '\n'
                                              'tests/rx/test_async_server.py '
                                              '\x1b[0;38;5;245m   83\x1b[0m  M '
                                              '\x1b[31m[S] starting processing '
                                              'pipelines for jobs and '
                                              'incomming data\x1b[0m\n'
                                              '\x1b[0;38;5;245m   83\x1b[0m  M '
                                              '\x1b[31m[S] \x1b[0m\n'
                                              '\x1b[0;38;5;245m   83\x1b[0m  1 '
                                              '\x1b[31m[S] \x1b[0m\n'
                                              '\x1b[0;38;5;245m   83\x1b[0m  1 '
                                              '\x1b[31m[S] starting server at '
                                              '50000\x1b[0m\n'
                                              '\x1b[0;38;5;245m  141\x1b[0m  2 '
                                              '\x1b[32m[1] Sending job\x1b[0m\n'
                                              '\x1b[0;38;5;245m  142\x1b[0m  3 '
                                              '\x1b[33m[2] Sending job\x1b[0m\n'
                                              '\x1b[0;38;5;245m  143\x1b[0m  4 '
                                              '\x1b[34m[3] Sending job\x1b[0m\n'
                                              '\x1b[0;38;5;245m  148\x1b[0m  5 '
                                              '\x1b[31m[S] running job '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m  449\x1b[0m  5 '
                                              '\x1b[31m[S] got result part 0 '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m  450\x1b[0m  4 '
                                              "\x1b[34m[3] got chunk {'res': "
                                              "'job3 result 0', 'nr': 0, 'dt': "
                                              '302}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  750\x1b[0m  5 '
                                              '\x1b[31m[S] got result part 1 '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m  750\x1b[0m  4 '
                                              "\x1b[34m[3] got chunk {'res': "
                                              "'job3 result 1', 'nr': 1, 'dt': "
                                              '603}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1050\x1b[0m  5 '
                                              '\x1b[31m[S] got result part 2 '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1051\x1b[0m  4 '
                                              "\x1b[34m[3] got chunk {'res': "
                                              "'job3 result 2', 'nr': 2, 'dt': "
                                              '903}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1352\x1b[0m  6 '
                                              '\x1b[31m[S] closing request '
                                              'socket\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1353\x1b[0m  7 '
                                              '\x1b[31m[S] running job '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1353\x1b[0m  4 '
                                              '\x1b[34m[3] done client\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1454\x1b[0m  7 '
                                              '\x1b[31m[S] got result part 0 '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1457\x1b[0m  2 '
                                              "\x1b[32m[1] got chunk {'res': "
                                              "'job1 result 0', 'nr': 0, 'dt': "
                                              '1306}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1556\x1b[0m  7 '
                                              '\x1b[31m[S] got result part 1 '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1557\x1b[0m  2 '
                                              "\x1b[32m[1] got chunk {'res': "
                                              "'job1 result 1', 'nr': 1, 'dt': "
                                              '1408}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1657\x1b[0m  7 '
                                              '\x1b[31m[S] got result part 2 '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1658\x1b[0m  2 '
                                              "\x1b[32m[1] got chunk {'res': "
                                              "'job1 result 2', 'nr': 2, 'dt': "
                                              '1509}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1758\x1b[0m  8 '
                                              '\x1b[31m[S] closing request '
                                              'socket\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1758\x1b[0m  9 '
                                              '\x1b[31m[S] running job '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1759\x1b[0m  2 '
                                              '\x1b[32m[1] done client\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1959\x1b[0m  9 '
                                              '\x1b[31m[S] got result part 0 '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1960\x1b[0m  3 '
                                              "\x1b[33m[2] got chunk {'res': "
                                              "'job2 result 0', 'nr': 0, 'dt': "
                                              '1811}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 2160\x1b[0m  9 '
                                              '\x1b[31m[S] got result part 1 '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m 2161\x1b[0m  3 '
                                              "\x1b[33m[2] got chunk {'res': "
                                              "'job2 result 1', 'nr': 1, 'dt': "
                                              '2012}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 2361\x1b[0m  9 '
                                              '\x1b[31m[S] got result part 2 '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m 2362\x1b[0m  3 '
                                              "\x1b[33m[2] got chunk {'res': "
                                              "'job2 result 2', 'nr': 2, 'dt': "
                                              '2213}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 2563\x1b[0m 10 '
                                              '\x1b[31m[S] closing request '
                                              'socket\x1b[0m\n'
                                              '\x1b[0;38;5;245m 2563\x1b[0m  3 '
                                              '\x1b[33m[2] done client\x1b[0m\n'
                                              '\x1b[0;38;5;245m 2595\x1b[0m  M '
                                              '\x1b[34m[3] all_done\x1b[0m\n'
                                              '.\n'
                                              '\n'
                                              '======================= 1 '
                                              'passed, 1 deselected in 2.72s '
                                              '========================'}],
 '73c02eb6f6524b1bab84ccaa733260d2': {'cmd': '$ cat tests/rx/tools.py',
                                      'res': 'import time\n'
                                             'import sys\n'
                                             'from threading import '
                                             'current_thread\n'
                                             'import gevent\n'
                                             '\n'
                                             '\n'
                                             'now = lambda: int(time.time() * '
                                             '1000)\n'
                                             't0 = now()\n'
                                             'dt = lambda: now() - t0\n'
                                             'thread = lambda: '
                                             "current_thread().name.replace('Dummy-', "
                                             "'').replace('MainThread', 'M')\n"
                                             'gray = '
                                             "'\\x1b[0;38;5;245m%s\\x1b[0m'\n"
                                             '\n'
                                             '\n'
                                             'def print(*a, p=print, who=0, '
                                             '**kw):\n'
                                             "    pre = '%s %2s ' % (gray % "
                                             "('%5s' % dt()), thread())\n"
                                             "    msg = ' '.join([str(i) for i "
                                             'in a])\n'
                                             "    msg = '\\x1b[3%sm[%s] "
                                             "%s\\x1b[0m' % (who + 1, who or "
                                             "'S', msg)\n"
                                             '    p(pre + msg, **kw)\n'
                                             '    return a[0]\n'
                                             '\n'
                                             '\n'
                                             '#  --------------------   quick '
                                             'test follows '
                                             '-------------------------------------------\n'
                                             "if __name__ == '__main__':\n"
                                             '    from gevent import monkey\n'
                                             '\n'
                                             '    sleep, asyn = gevent.sleep, '
                                             'gevent.spawn\n'
                                             '    if sys.argv[-1] == '
                                             "'patched':\n"
                                             '        monkey.patch_all()\n'
                                             '        assert time.sleep == '
                                             'gevent.sleep  # since patched\n'
                                             "    print('msg 1')\n"
                                             '\n'
                                             '    def f(who):\n'
                                             '        sleep(0.05)\n'
                                             "        print('async msg', "
                                             'who=who)\n'
                                             '\n'
                                             '    asyn(f, 2)\n'
                                             '    asyn(f, 3)\n'
                                             '    asyn(f, 0)\n'
                                             '\n'
                                             '    sleep(0.1)\n'
                                             "    print('msg 3', who=4)\n"},
 '73c02eb6f6524b1bab84ccaa733260d2_': {'cmd': '$ cat tests/rx/server.py',
                                       'res': '#!/usr/bin/env python\n'
                                              'import json\n'
                                              'import sys\n'
                                              'import time\n'
                                              'from functools import partial\n'
                                              '\n'
                                              'import gevent\n'
                                              'import gevent.queue\n'
                                              'import rx as Rx\n'
                                              'from flask import Flask, '
                                              'stream_with_context\n'
                                              'from gevent import monkey\n'
                                              'from gevent.pywsgi import '
                                              'WSGIServer\n'
                                              'from rx import operators as rx\n'
                                              'from rx.scheduler.eventloop '
                                              'import GEventScheduler as GS\n'
                                              'from tools import gevent, now, '
                                              'print\n'
                                              'from werkzeug.debug import '
                                              'DebuggedApplication\n'
                                              'from werkzeug.serving import '
                                              'run_with_reloader\n'
                                              '\n'
                                              "sys.path.append(__file__.rsplit('/', "
                                              '1)[0])\n'
                                              '\n'
                                              '\n'
                                              'monkey.patch_all()\n'
                                              'app = Flask(__name__)\n'
                                              'GS = GS(gevent)\n'
                                              'jobs = Rx.subject.Subject()\n'
                                              'results = Rx.subject.Subject()\n'
                                              'flush_response = lambda q: '
                                              'q.put(StopIteration)  # closing '
                                              'the socket\n'
                                              'wait = lambda dt: time.sleep(dt '
                                              '/ 1000.0)\n'
                                              'asyn = lambda: '
                                              'rx.observe_on(GS)  # put '
                                              'pipeline onto a new greenlet\n'
                                              '\n'
                                              '\n'
                                              'class J:\n'
                                              '    """Job Running Pipeline '
                                              'Functions"""\n'
                                              '\n'
                                              '    def _run_job(job):\n'
                                              '        """syncronous job '
                                              'running"""\n'
                                              '        # how is the job '
                                              '(transport, behaviour, ...):\n'
                                              '        _, job = '
                                              "job['meta'].pop, job['job']\n"
                                              '        parts, dt, q, ts = '
                                              "_('parts'), _('dt'), _('req'), "
                                              "_('ts')\n"
                                              "        print('running job', "
                                              'job)\n'
                                              '        for c in range(parts):\n'
                                              '            wait(dt)\n'
                                              "            print('got result "
                                              "part', c, job)\n"
                                              '            res = {\n'
                                              "                'res': '%s "
                                              "result %s' % (job, c),\n"
                                              "                'nr': c,\n"
                                              "                'dt': now() - "
                                              'ts,\n'
                                              "                'req': q,\n"
                                              '            }\n'
                                              '            '
                                              'results.on_next(res)\n'
                                              '        # Closing the req '
                                              'socket after all parts are '
                                              'there. Normally elsewhere, we '
                                              'do\n'
                                              '        # not know that '
                                              "normally or 'all there' is "
                                              'never.\n'
                                              '        # But that can be done '
                                              'from anywhere - e.g. at cancel '
                                              'from the client\n'
                                              '        # or when his socket '
                                              'closes:\n'
                                              '        wait(dt)\n'
                                              '        flush_response(q)\n'
                                              '\n'
                                              '    run_job = rx.map(_run_job)\n'
                                              '\n'
                                              '\n'
                                              'class R:\n'
                                              '    """Results Handling '
                                              'Functions"""\n'
                                              '\n'
                                              '    def '
                                              'interested_clients(res):\n'
                                              '        """Work via a central '
                                              'registry of clients who want '
                                              'job results"""\n'
                                              '        # here we just added '
                                              '"them" directly into the '
                                              'result:\n'
                                              '        return '
                                              "[res.pop('req')]\n"
                                              '\n'
                                              '    def _send_response(res):\n'
                                              '        clients = '
                                              'R.interested_clients(res)\n'
                                              '        ser = json.dumps(res) + '
                                              "'\\r\\n'\n"
                                              '        [c.put(ser) for c in '
                                              'clients]\n'
                                              '        return res\n'
                                              '\n'
                                              '    send_response = '
                                              'rx.map(_send_response)\n'
                                              '\n'
                                              '\n'
                                              'def new_job(job, meta):\n'
                                              '    """Production decoupled '
                                              'from repsonse sending"""\n'
                                              "    jobs.on_next({'job': job, "
                                              "'meta': meta})\n"
                                              '\n'
                                              '\n'
                                              "@app.route('/<job>/<int:parts>/<int:dt>')\n"
                                              'def index(job, parts, dt):\n'
                                              '    """\n'
                                              '    The request handling '
                                              'greenlet.\n'
                                              '\n'
                                              '    The client can parametrize '
                                              'how many data parts the job '
                                              'result should have - and\n'
                                              "    when they 'arrive'.\n"
                                              '\n'
                                              '    Creates a queue which, when '
                                              'seing an item, will cause a '
                                              'chunk response\n'
                                              '    """\n'
                                              '    # eventhandlers can produce '
                                              "here and we'll send to the "
                                              'client:\n'
                                              '    q = gevent.queue.Queue()\n'
                                              '\n'
                                              '    def generate():\n'
                                              '        for data in q:\n'
                                              '            yield data\n'
                                              "        print('closing request "
                                              "socket')\n"
                                              '\n'
                                              "    meta = {'parts': parts, "
                                              "'dt': dt, 'req': q, 'ts': "
                                              'now()}\n'
                                              '    new_job(job, meta)\n'
                                              "    _ = 'application/json'\n"
                                              '    return '
                                              'app.response_class(stream_with_context(generate()), '
                                              'mimetype=_)\n'
                                              '\n'
                                              '\n'
                                              '# '
                                              '------------------------------------------------------------------------------- '
                                              'server\n'
                                              'def '
                                              'reconfigure_server_pipelines(pipelines, '
                                              'subs=[0, 0]):\n'
                                              "    print('starting processing "
                                              'pipelines for jobs and '
                                              "incomming data')\n"
                                              '    if subs[0]:\n'
                                              "        print('stopping old "
                                              "pipeline')\n"
                                              '        [s.dispose() for s in '
                                              'subs]\n'
                                              '\n'
                                              '    for i in [0, 1]:\n'
                                              '        s = [jobs, '
                                              'results][i].pipe(asyn(), '
                                              '*pipelines[i])\n'
                                              '        subs[i] = '
                                              's.subscribe()\n'
                                              '    return True\n'
                                              '\n'
                                              '\n'
                                              'def run_server():\n'
                                              "    print('')\n"
                                              "    print('starting server at "
                                              "50000')\n"
                                              '    http_server = '
                                              "WSGIServer(('', 50000), "
                                              'DebuggedApplication(app))\n'
                                              '    '
                                              'http_server.serve_forever()\n'},
 '73c02eb6f6524b1bab84ccaa733260d2__': {'cmd': '$ cat '
                                               'tests/rx/test_async_server.py',
                                        'res': 'import json\n'
                                               'import os\n'
                                               'import sys\n'
                                               'import time\n'
                                               'from functools import partial\n'
                                               '\n'
                                               'from server import J, R, Rx, '
                                               'asyn, '
                                               'reconfigure_server_pipelines, '
                                               'run_server, rx, wait\n'
                                               'from tools import gevent, '
                                               'print\n'
                                               '\n'
                                               "sys.path.append(__file__.rsplit('/', "
                                               '1)[0])  # noqa\n'
                                               'gevent.spawn(run_server)\n'
                                               '\n'
                                               'done_clients = []\n'
                                               '\n'
                                               '\n'
                                               'def test_server_one():\n'
                                               '    """Keeping order but '
                                               'processing jobs (and '
                                               'responses) one after the '
                                               'other\n'
                                               "    Whichever clients' "
                                               'requests is first on the '
                                               'server will see all chunks '
                                               'first:\n'
                                               '    """\n'
                                               '    p = [[J.run_job], '
                                               '[R.send_response]]\n'
                                               '    '
                                               'reconfigure_server_pipelines(p) '
                                               'and send_requests()\n'
                                               '\n'
                                               '\n'
                                               'def test_server_two():\n'
                                               '    """Here we run the jobs '
                                               'within parallel greenlets"""\n'
                                               '    p = [\n'
                                               '        [rx.flat_map(lambda '
                                               'job: Rx.just(job).pipe(asyn(), '
                                               'J.run_job)),],\n'
                                               '        [R.send_response],\n'
                                               '    ]\n'
                                               '    '
                                               'reconfigure_server_pipelines(p) '
                                               'and send_requests()\n'
                                               '\n'
                                               '\n'
                                               '# '
                                               '------------------------------------------------------------------------------- '
                                               'Tools\n'
                                               '# here spawn 3 greenlets, '
                                               'sending 3 requests in '
                                               'parallel, simulating 3 '
                                               'clients"""\n'
                                               '# they iterate of the chunks '
                                               'from the server and print '
                                               'them\n'
                                               'def send_requests():\n'
                                               '    # yes we can reconfigure '
                                               'the pipeline while running;\n'
                                               '    done_clients.clear()\n'
                                               "    print('')\n"
                                               '    for client in 1, 2, 3:\n'
                                               '        s = '
                                               'partial(send_job_req_to_api_server, '
                                               'client=client)\n'
                                               '        gevent.spawn(s)\n'
                                               '    while not '
                                               'len(done_clients) == 3:\n'
                                               '        wait(100)\n'
                                               "    print('all_done', "
                                               'who=client)\n'
                                               '\n'
                                               '\n'
                                               'def '
                                               'send_job_req_to_api_server(client):\n'
                                               '    from requests import get\n'
                                               '\n'
                                               "    print('Sending job', "
                                               'who=client)\n'
                                               '    j, url = json.loads, '
                                               "'http://127.0.0.1:50000/job%s/3/%s'\n"
                                               '    chunks = get(url % '
                                               '(client, 100 * client), '
                                               'stream=True)\n'
                                               "    [print('got chunk', j(r), "
                                               'who=client) for r in '
                                               'chunks.iter_lines()]\n'
                                               "    print('done client', "
                                               'who=client)\n'
                                               '    '
                                               'done_clients.append(client)\n'},
 '919b84a7ec178a1ca50a15fa091db2d1': [{'cmd': 'pytest -xs '
                                              'tests/rx/test_async_server.py '
                                              '-k two 2>/dev/null',
                                       'res': '$ pytest -xs '
                                              'tests/rx/test_async_server.py '
                                              '-k two 2>/dev/null\n'
                                              '============================= '
                                              'test session starts '
                                              '==============================\n'
                                              'platform linux -- Python '
                                              '3.9.10, pytest-6.2.5, '
                                              'py-1.11.0, pluggy-1.0.0\n'
                                              'Using '
                                              '--randomly-seed=730152330\n'
                                              'rootdir: /home/gk/repos\n'
                                              'plugins: forked-1.4.0, '
                                              'randomly-3.11.0, cov-2.12.1, '
                                              'xdist-2.5.0, sugar-0.9.4\n'
                                              'collected 2 items / 1 '
                                              'deselected / 1 selected\n'
                                              '\n'
                                              'tests/rx/test_async_server.py '
                                              '\x1b[0;38;5;245m   76\x1b[0m  M '
                                              '\x1b[31m[S] starting processing '
                                              'pipelines for jobs and '
                                              'incomming data\x1b[0m\n'
                                              '\x1b[0;38;5;245m   76\x1b[0m  M '
                                              '\x1b[31m[S] \x1b[0m\n'
                                              '\x1b[0;38;5;245m   77\x1b[0m  1 '
                                              '\x1b[31m[S] \x1b[0m\n'
                                              '\x1b[0;38;5;245m   77\x1b[0m  1 '
                                              '\x1b[31m[S] starting server at '
                                              '50000\x1b[0m\n'
                                              '\x1b[0;38;5;245m  109\x1b[0m  2 '
                                              '\x1b[32m[1] Sending job\x1b[0m\n'
                                              '\x1b[0;38;5;245m  110\x1b[0m  3 '
                                              '\x1b[33m[2] Sending job\x1b[0m\n'
                                              '\x1b[0;38;5;245m  111\x1b[0m  4 '
                                              '\x1b[34m[3] Sending job\x1b[0m\n'
                                              '\x1b[0;38;5;245m  115\x1b[0m  6 '
                                              '\x1b[31m[S] running job '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m  116\x1b[0m  8 '
                                              '\x1b[31m[S] running job '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m  116\x1b[0m 10 '
                                              '\x1b[31m[S] running job '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m  217\x1b[0m  8 '
                                              '\x1b[31m[S] got result part 0 '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m  218\x1b[0m  2 '
                                              "\x1b[32m[1] got chunk {'res': "
                                              "'job1 result 0', 'nr': 0, 'dt': "
                                              '103}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  317\x1b[0m 10 '
                                              '\x1b[31m[S] got result part 0 '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m  317\x1b[0m  8 '
                                              '\x1b[31m[S] got result part 1 '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m  318\x1b[0m  2 '
                                              "\x1b[32m[1] got chunk {'res': "
                                              "'job1 result 1', 'nr': 1, 'dt': "
                                              '203}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  318\x1b[0m  3 '
                                              "\x1b[33m[2] got chunk {'res': "
                                              "'job2 result 0', 'nr': 0, 'dt': "
                                              '202}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  416\x1b[0m  6 '
                                              '\x1b[31m[S] got result part 0 '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m  417\x1b[0m  4 '
                                              "\x1b[34m[3] got chunk {'res': "
                                              "'job3 result 0', 'nr': 0, 'dt': "
                                              '302}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  418\x1b[0m  8 '
                                              '\x1b[31m[S] got result part 2 '
                                              'job1\x1b[0m\n'
                                              '\x1b[0;38;5;245m  419\x1b[0m  2 '
                                              "\x1b[32m[1] got chunk {'res': "
                                              "'job1 result 2', 'nr': 2, 'dt': "
                                              '304}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  518\x1b[0m 10 '
                                              '\x1b[31m[S] got result part 1 '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m  518\x1b[0m  3 '
                                              "\x1b[33m[2] got chunk {'res': "
                                              "'job2 result 1', 'nr': 1, 'dt': "
                                              '403}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  518\x1b[0m 11 '
                                              '\x1b[31m[S] closing request '
                                              'socket\x1b[0m\n'
                                              '\x1b[0;38;5;245m  519\x1b[0m  2 '
                                              '\x1b[32m[1] done client\x1b[0m\n'
                                              '\x1b[0;38;5;245m  718\x1b[0m  6 '
                                              '\x1b[31m[S] got result part 1 '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m  718\x1b[0m  4 '
                                              "\x1b[34m[3] got chunk {'res': "
                                              "'job3 result 1', 'nr': 1, 'dt': "
                                              '604}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  719\x1b[0m 10 '
                                              '\x1b[31m[S] got result part 2 '
                                              'job2\x1b[0m\n'
                                              '\x1b[0;38;5;245m  719\x1b[0m  3 '
                                              "\x1b[33m[2] got chunk {'res': "
                                              "'job2 result 2', 'nr': 2, 'dt': "
                                              '604}\x1b[0m\n'
                                              '\x1b[0;38;5;245m  920\x1b[0m 12 '
                                              '\x1b[31m[S] closing request '
                                              'socket\x1b[0m\n'
                                              '\x1b[0;38;5;245m  920\x1b[0m  3 '
                                              '\x1b[33m[2] done client\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1019\x1b[0m  6 '
                                              '\x1b[31m[S] got result part 2 '
                                              'job3\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1019\x1b[0m  4 '
                                              "\x1b[34m[3] got chunk {'res': "
                                              "'job3 result 2', 'nr': 2, 'dt': "
                                              '905}\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1320\x1b[0m 13 '
                                              '\x1b[31m[S] closing request '
                                              'socket\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1321\x1b[0m  4 '
                                              '\x1b[34m[3] done client\x1b[0m\n'
                                              '\x1b[0;38;5;245m 1385\x1b[0m  M '
                                              '\x1b[34m[3] all_done\x1b[0m\n'
                                              '.\n'
                                              '\n'
                                              '======================= 1 '
                                              'passed, 1 deselected in 1.51s '
                                              '========================'}]}