{'73c02eb6f6524b1bab84ccaa733260d2': {'cmd': '$ cat .github/workflows/ci.yml',
                                      'res': 'name: ci\n'
                                             '\n'
                                             'on:\n'
                                             '  push:\n'
                                             '    branches:\n'
                                             '      - master\n'
                                             '  pull_request:\n'
                                             '    branches:\n'
                                             '      - master\n'
                                             '\n'
                                             'defaults:\n'
                                             '  run:\n'
                                             '    shell: bash\n'
                                             '\n'
                                             'env:\n'
                                             '  LANG: "en_US.utf-8"\n'
                                             '  LC_ALL: "en_US.utf-8"\n'
                                             '  POETRY_VIRTUALENVS_IN_PROJECT: '
                                             '"true"\n'
                                             '  PYTHONIOENCODING: "UTF-8"\n'
                                             '  PROJECT: "blog"\n'
                                             '  MC: "/home/runner/miniconda3"\n'
                                             '  PATH: '
                                             '"$(MC)/bin:/home/runner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:"\n'
                                             '  versioning: calver # for '
                                             'git-changelog\n'
                                             '\n'
                                             'jobs:\n'
                                             '  tests:\n'
                                             '    name: Tests (${{ '
                                             'matrix.python-version }}, ${{ '
                                             'matrix.os }})\n'
                                             '    runs-on: ${{ matrix.os }}\n'
                                             '    strategy:\n'
                                             '      fail-fast: false\n'
                                             '      max-parallel: 6\n'
                                             '      matrix:\n'
                                             '        os: ["ubuntu-latest"]\n'
                                             '        python-version: ["3.7", '
                                             '"3.8"]\n'
                                             '    steps:\n'
                                             '      - uses: '
                                             'actions/checkout@v2\n'
                                             '      - name: Set up the '
                                             'Miniconda Root Cache\n'
                                             '        uses: actions/cache@v2\n'
                                             '        env:\n'
                                             '          cache_name: '
                                             'cache-miniconda-root\n'
                                             '        with:\n'
                                             '          path: ~/miniconda3\n'
                                             '          key: ${{ runner.os '
                                             '}}-build-${{ env.cache_name }}\n'
                                             '      - name: Install Miniconda '
                                             'Root\n'
                                             '        shell: bash -l {0}\n'
                                             '        run: "source ./make && '
                                             'make ci_conda_root_env"\n'
                                             '      - name: Conda info\n'
                                             '        shell: bash -l {0}\n'
                                             '        run: conda info\n'
                                             '      - name: Set up the '
                                             'Miniconda Envs Cache\n'
                                             '        # they delete unused '
                                             'ones after 7 days.\n'
                                             '        uses: actions/cache@v2\n'
                                             '        env:\n'
                                             '          cache_name: '
                                             'cache-miniconda-envs-${{ '
                                             'env.PROJECT }}_py${{ '
                                             'matrix.python-version }}_${{ '
                                             "hashFiles('pyproject.toml', "
                                             "'scripts/**') }}\n"
                                             '        with:\n'
                                             '          path: '
                                             '~/miniconda3/envs/${{ '
                                             'env.PROJECT }}_py${{ '
                                             'matrix.python-version }}\n'
                                             '          key: ${{ runner.os '
                                             '}}-build-${{ env.cache_name }}\n'
                                             '\n'
                                             '      - name: Install Miniconda '
                                             'PyEnv\n'
                                             '        shell: bash -l {0}\n'
                                             '        env:\n'
                                             '          pyver: "${{ '
                                             'matrix.python-version }}"\n'
                                             '        run: "source ./make && '
                                             'make && make ci_conda_py_env"\n'
                                             '\n'
                                             '      - name: Run tests\n'
                                             '        shell: bash -l {0}\n'
                                             '        env:\n'
                                             '          pyver: "${{ '
                                             'matrix.python-version }}"\n'
                                             '        run: "source ./make && '
                                             'activate_venv && make tests"\n'
                                             '\n'
                                             '      - name: Test Docs '
                                             'LiterateProgramming\n'
                                             '        shell: bash -l {0}\n'
                                             '        env:\n'
                                             '          pyver: "${{ '
                                             'matrix.python-version }}"\n'
                                             '        run: "source ./make && '
                                             'activate_venv && make docs"\n'
                                             '\n'
                                             '      - name: Deploy Docs\n'
                                             '        shell: bash -l {0}\n'
                                             '        env:\n'
                                             '          pyver: "${{ '
                                             'matrix.python-version }}"\n'
                                             '        run: "source ./make && '
                                             'activate_venv && ${{ env.pyver '
                                             "== '3.9' && 'mkdocs gh-deploy "
                                             '--force\' || true }}"\n'}}