{'be96428f7be04caab7ab63cc361463c1': {'formatted': '\n'
                                                   '\n'
                                                   '\n'
                                                   '\n'
                                                   '# Changelog\n'
                                                   'All notable changes to '
                                                   'this project will be '
                                                   'documented in this file.\n'
                                                   '\n'
                                                   'The format is based on '
                                                   '[Keep a '
                                                   'Changelog](http://keepachangelog.com/en/1.0.0/).\n'
                                                   '\n'
                                                   'This project adheres to '
                                                   '[CalVer '
                                                   'Versioning](http://calver.org) '
                                                   '![](https://img.shields.io/badge/calver-YYYY.M.D-22bfda.svg).\n'
                                                   '\n'
                                                   '## '
                                                   '[2021.9.0](https://github.com/AXGKl/blog/releases/tag/2021.9.0)\n'
                                                   '<small>[Compare with '
                                                   '2021.8.18](https://github.com/AXGKl/blog/compare/2021.8.18...2021.9.0)</small>\n'
                                                   '\n'
                                                   '### Bug Fixes\n'
                                                   '- Update to newer '
                                                   'docutools '
                                                   '([a8445a6](https://github.com/AXGKl/blog/commit/a8445a68bd8c7693147438d7b1b11ba2c925d5ad) '
                                                   'by Gunther Klessinger).\n'
                                                   '- Mdreplace needs in this '
                                                   'version one with :all: '
                                                   '(bug) '
                                                   '([d332bd2](https://github.com/AXGKl/blog/commit/d332bd2cf0c9c510aff20738b3b4944c6a147851) '
                                                   'by Gunther Klessinger).\n'
                                                   '\n'
                                                   '### Features\n'
                                                   '- Mkdocs page '
                                                   '([9198ccd](https://github.com/AXGKl/blog/commit/9198ccdc17e1390ef6d41cee35d231e75ea250eb) '
                                                   'by Gunther Klessinger).\n'
                                                   '- Better logs '
                                                   '([d48303b](https://github.com/AXGKl/blog/commit/d48303b1245c73dd3080acaecef450ba111a13d1) '
                                                   'by Gunther Klessinger).\n'
                                                   '\n'
                                                   '\n'
                                                   '## '
                                                   '[2021.8.18](https://github.com/AXGKl/blog/releases/tag/2021.8.18)\n'
                                                   '<small>[Compare with '
                                                   '2021.8.13](https://github.com/AXGKl/blog/compare/2021.8.13...2021.8.18)</small>\n'
                                                   '\n'
                                                   '### Bug Fixes\n'
                                                   '- Link '
                                                   '([4d91456](https://github.com/AXGKl/blog/commit/4d91456bca8b8afac97e93d88b77709d7a772c41) '
                                                   'by Gunther Klessinger).\n'
                                                   '- K9s link '
                                                   '([b89f0bd](https://github.com/AXGKl/blog/commit/b89f0bdc06808a53b92e652f8c292b2bfe396e2d) '
                                                   'by Gunther Klessinger).\n'
                                                   '\n'
                                                   '### Features\n'
                                                   '- New make system '
                                                   '([b7957bc](https://github.com/AXGKl/blog/commit/b7957bc58e91142a087ff35346eb5c4f0ffca90d) '
                                                   'by Gunther Klessinger).\n'
                                                   '- K9s '
                                                   '([55967b6](https://github.com/AXGKl/blog/commit/55967b6dd9dcc4674b98c386cf17ae3f815477f3) '
                                                   'by Gunther Klessinger).\n'
                                                   '- Mysql deploy fully on '
                                                   'k8s '
                                                   '([f9e30d6](https://github.com/AXGKl/blog/commit/f9e30d680ac329b25024111a28cf64a86de31d7a) '
                                                   'by Gunther Klessinger).\n'
                                                   '\n'
                                                   '\n'
                                                   '## '
                                                   '[2021.8.13](https://github.com/AXGKl/blog/releases/tag/2021.8.13)\n'
                                                   '<small>[Compare with '
                                                   '2021.8.12](https://github.com/AXGKl/blog/compare/2021.8.12...2021.8.13)</small>\n'
                                                   '\n'
                                                   '### Features\n'
                                                   '- Rewordign '
                                                   '([7a6ad14](https://github.com/AXGKl/blog/commit/7a6ad14eb6e08823a2ec00852c8d633d973234c0) '
                                                   'by Gunther Klessinger).\n'
                                                   '- Added content from '
                                                   'previous attemtps '
                                                   '([dda22bf](https://github.com/AXGKl/blog/commit/dda22bf07d89d6488f304a1d1e9b726c22b61665) '
                                                   'by Gunther Klessinger).\n'
                                                   '\n'
                                                   '\n'
                                                   '## '
                                                   '[2021.8.12](https://github.com/AXGKl/blog/releases/tag/2021.8.12)\n'
                                                   '<small>[Compare with '
                                                   '2021.8.11](https://github.com/AXGKl/blog/compare/2021.8.11...2021.8.12)</small>\n'
                                                   '\n'
                                                   '\n'
                                                   '## '
                                                   '[2021.8.11](https://github.com/AXGKl/blog/releases/tag/2021.8.11)\n'
                                                   '<small>[Compare with first '
                                                   'commit](https://github.com/AXGKl/blog/compare/45bc18a6ab9ed9d2ac280ae113899a55ee4d827c...2021.8.11)</small>\n'
                                                   '\n'
                                                   '\n',
                                      'res': '\n'
                                             '\n'
                                             '\n'
                                             '\n'
                                             '# Changelog\n'
                                             'All notable changes to this '
                                             'project will be documented in '
                                             'this file.\n'
                                             '\n'
                                             'The format is based on [Keep a '
                                             'Changelog](http://keepachangelog.com/en/1.0.0/).\n'
                                             '\n'
                                             'This project adheres to [CalVer '
                                             'Versioning](http://calver.org) '
                                             '![](https://img.shields.io/badge/calver-YYYY.M.D-22bfda.svg).\n'
                                             '\n'
                                             '## '
                                             '[2021.9.0](https://github.com/AXGKl/blog/releases/tag/2021.9.0)\n'
                                             '<small>[Compare with '
                                             '2021.8.18](https://github.com/AXGKl/blog/compare/2021.8.18...2021.9.0)</small>\n'
                                             '\n'
                                             '### Bug Fixes\n'
                                             '- Update to newer docutools '
                                             '([a8445a6](https://github.com/AXGKl/blog/commit/a8445a68bd8c7693147438d7b1b11ba2c925d5ad) '
                                             'by Gunther Klessinger).\n'
                                             '- Mdreplace needs in this '
                                             'version one with :all: (bug) '
                                             '([d332bd2](https://github.com/AXGKl/blog/commit/d332bd2cf0c9c510aff20738b3b4944c6a147851) '
                                             'by Gunther Klessinger).\n'
                                             '\n'
                                             '### Features\n'
                                             '- Mkdocs page '
                                             '([9198ccd](https://github.com/AXGKl/blog/commit/9198ccdc17e1390ef6d41cee35d231e75ea250eb) '
                                             'by Gunther Klessinger).\n'
                                             '- Better logs '
                                             '([d48303b](https://github.com/AXGKl/blog/commit/d48303b1245c73dd3080acaecef450ba111a13d1) '
                                             'by Gunther Klessinger).\n'
                                             '\n'
                                             '\n'
                                             '## '
                                             '[2021.8.18](https://github.com/AXGKl/blog/releases/tag/2021.8.18)\n'
                                             '<small>[Compare with '
                                             '2021.8.13](https://github.com/AXGKl/blog/compare/2021.8.13...2021.8.18)</small>\n'
                                             '\n'
                                             '### Bug Fixes\n'
                                             '- Link '
                                             '([4d91456](https://github.com/AXGKl/blog/commit/4d91456bca8b8afac97e93d88b77709d7a772c41) '
                                             'by Gunther Klessinger).\n'
                                             '- K9s link '
                                             '([b89f0bd](https://github.com/AXGKl/blog/commit/b89f0bdc06808a53b92e652f8c292b2bfe396e2d) '
                                             'by Gunther Klessinger).\n'
                                             '\n'
                                             '### Features\n'
                                             '- New make system '
                                             '([b7957bc](https://github.com/AXGKl/blog/commit/b7957bc58e91142a087ff35346eb5c4f0ffca90d) '
                                             'by Gunther Klessinger).\n'
                                             '- K9s '
                                             '([55967b6](https://github.com/AXGKl/blog/commit/55967b6dd9dcc4674b98c386cf17ae3f815477f3) '
                                             'by Gunther Klessinger).\n'
                                             '- Mysql deploy fully on k8s '
                                             '([f9e30d6](https://github.com/AXGKl/blog/commit/f9e30d680ac329b25024111a28cf64a86de31d7a) '
                                             'by Gunther Klessinger).\n'
                                             '\n'
                                             '\n'
                                             '## '
                                             '[2021.8.13](https://github.com/AXGKl/blog/releases/tag/2021.8.13)\n'
                                             '<small>[Compare with '
                                             '2021.8.12](https://github.com/AXGKl/blog/compare/2021.8.12...2021.8.13)</small>\n'
                                             '\n'
                                             '### Features\n'
                                             '- Rewordign '
                                             '([7a6ad14](https://github.com/AXGKl/blog/commit/7a6ad14eb6e08823a2ec00852c8d633d973234c0) '
                                             'by Gunther Klessinger).\n'
                                             '- Added content from previous '
                                             'attemtps '
                                             '([dda22bf](https://github.com/AXGKl/blog/commit/dda22bf07d89d6488f304a1d1e9b726c22b61665) '
                                             'by Gunther Klessinger).\n'
                                             '\n'
                                             '\n'
                                             '## '
                                             '[2021.8.12](https://github.com/AXGKl/blog/releases/tag/2021.8.12)\n'
                                             '<small>[Compare with '
                                             '2021.8.11](https://github.com/AXGKl/blog/compare/2021.8.11...2021.8.12)</small>\n'
                                             '\n'
                                             '\n'
                                             '## '
                                             '[2021.8.11](https://github.com/AXGKl/blog/releases/tag/2021.8.11)\n'
                                             '<small>[Compare with first '
                                             'commit](https://github.com/AXGKl/blog/compare/45bc18a6ab9ed9d2ac280ae113899a55ee4d827c...2021.8.11)</small>\n'
                                             '\n'
                                             '\n'}}